### PR TITLE
json and tests, update to v0.4

### PR DESCRIPTION
**Pull request by szymonjanas**
- internal communication (server<=>engine) via tcp socket with JSON message format,
- engine: new communication routes management,
- engine: only json file database,
- server: new api routes funcs,
- improved logs in server and engine,
- server: new rest api 
- engine: add some utest
- add integration tests in python for engine api and engine <=> server <=> client (rest api).
- engine: add new method to run server
- engine: add new routes for run arguments,
- add basic documentation for engine and server,

### CODE REVIEW

**Comment by szymonjanas** [comment]
also added Travis CI build

**Comment by szymonjanas** [comment]
provide solutions for  #11  #10  #8

**Comment by szymonjanas** [comment]
@kbodanko @piotrlewandowski
🔔 review reminder 🔔

**Comment by piotrlewandowski** [comment]
Wow, that's a huge PR!

**Review by piotrlewandowski — APPROVED** [review]
Impressive job, well done mate!

**Pull request merged**
